services:
  - type: web
    name: luminous-photonics        # your existing service name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn photonics.wsgi:application"
    timeoutSeconds: 600             # 10-minute timeout

    # Serve your collected static files
    static: true
    staticPath: ./staticfiles       # your STATIC_ROOT

    # Serve your media uploads
    staticPublishPath: /app/media
    routes:
      - type: filesystem
        pathPrefix: /media
        publishPath: /app/media

    envVars:
      - key: SECRET_KEY
        fromDatabase:
          name: photonics-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: photonics-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      # … any other env vars you had …
