# Generated by Django 5.0.3 on 2025-03-06 01:20

from django_ckeditor_5.fields import CKEditor5Field  # updated import
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_blogpost_approved_blogpost_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=CKEditor5Field('Content', config_name='default', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
