# Generated by Django 5.0.3 on 2025-03-06 02:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_blogpost_content_alter_blogpost_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
