# Generated by Django 5.0.3 on 2025-03-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content_doc",
            field=models.FileField(blank=True, null=True, upload_to="blog_docs/"),
        ),
    ]
