# Generated by Django 5.0.3 on 2025-03-06 10:27

from django_ckeditor_5.fields import CKEditor5Field  # updated import
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_blogpost_content_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=CKEditor5Field('Content', config_name='default', blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
