# Generated by Django 5.0.3 on 2025-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_blogpost_content_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Meta description for SERP (a brief page summary)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Enter 3-5 keywords separated by commas",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title tag for browser tab (50-60 characters)",
                max_length=80,
                null=True,
            ),
        ),
    ]
